import { Ban, Bike, CalendarDays, Check, Eye, FileText, Mail, MapPin, MessageSquare, Pencil, Phone, Star, Wallet } from "lucide-react";
import Badge from "../components/ui/Badge";
import Button from "../components/ui/button";
import { deliveryPartners } from "../mock/vayzoApiMock";

const value = (item) => item || "--";
const initials = (name) => name.split(" ").map((part) => part[0]).join("").toUpperCase();
const Rows = ({ items }) => <div className="space-y-2 text-xs">{items.map(([label, item]) => <div key={label} className="flex gap-3"><span className="w-2/5 shrink-0 text-muted">{label}</span><span className="min-w-0 truncate font-medium text-foreground">{value(item)}</span></div>)}</div>;
const Card = ({ title, icon: Icon, children }) => <div className="rounded-xl border border-border bg-surface p-4 shadow-sm"><h3 className="mb-4 flex items-center gap-2 text-sm font-semibold text-foreground"><Icon size={16} className="text-primary" />{title}</h3>{children}</div>;

function DeliveryPartner() {
  const partner = deliveryPartners[0];
  const stats = [["Partner ID", partner.partnerId], ["Vehicle", partner.vehicleType], ["Vehicle Number", partner.vehicleNumber], ["Total Orders", partner.ordersCompleted], ["Completion Rate", partner.completionRate], ["Cancellation Rate", partner.cancellationRate], ["Total Earnings", `₹${partner.earnings}`], ["Today's Earnings", partner.todayEarnings], ["Last Order", partner.lastOrder]];
  const documents = ["Aadhaar Card", "Driving License", "PAN Card", "Profile Photo", "Vehicle RC Book", "Insurance"];
  const activities = ["Order delivered", "Earnings added", "Payout completed", "Profile information updated", "Document insurance uploaded"];
  return <section className="min-h-full bg-background p-4 sm:p-6"><div className="space-y-4">
    <header className="flex flex-wrap items-center justify-between gap-3 border-b border-border pb-4"><div><p className="text-xs text-muted">Dashboard &gt; Delivery Partners &gt; {partner.partnerId}</p><h1 className="mt-1 text-2xl font-semibold text-foreground">Delivery Partner Details</h1></div><div className="flex flex-wrap gap-2"><Button variant="secondary" size="sm"><MessageSquare size={15} className="mr-1.5" />Send Message</Button><Button variant="secondary" size="sm"><Ban size={15} className="mr-1.5" />Block Partner</Button><Button size="sm"><Pencil size={15} className="mr-1.5" />Edit Partner</Button></div></header>
    <div className="grid gap-4 rounded-xl border border-border bg-surface p-4 shadow-sm lg:grid-cols-[minmax(260px,1fr)_2fr]"><div className="flex items-center gap-4"><div className="flex h-24 w-24 shrink-0 items-center justify-center rounded-full bg-primary text-2xl font-semibold text-white">{initials(partner.name)}</div><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h2 className="text-xl font-semibold text-foreground">{partner.name}</h2><Badge variant="success" className="h-6">{partner.status}</Badge></div><p className="mt-2 flex items-center gap-1 text-sm text-amber-500"><Star size={15} fill="currentColor" />{partner.rating.toFixed(1)} <span className="text-muted">(Reviews)</span></p><p className="mt-2 flex items-center gap-2 text-xs text-muted"><Phone size={14} />{partner.mobileNumber}</p><p className="mt-1 flex items-center gap-2 truncate text-xs text-muted"><Mail size={14} />{partner.email}</p><p className="mt-1 flex items-center gap-2 text-xs text-muted"><MapPin size={14} />{partner.city}</p><Badge variant="success" className="mt-2 h-6">● Online</Badge></div></div><div className="grid grid-cols-2 gap-x-4 gap-y-3 border-t border-border pt-4 text-xs sm:grid-cols-3 lg:border-l lg:border-t-0 lg:pl-5 lg:pt-0">{stats.map(([label, item]) => <div key={label} className="min-w-0"><p className="text-muted">{label}</p><p className="mt-1 truncate font-semibold text-foreground">{value(item)}</p></div>)}</div></div>
    <nav className="flex gap-5 overflow-hidden border-b border-border text-xs font-semibold text-muted">{["Overview", "Documents", "Earnings", "Orders", "Payouts", "Performance", "Activity Logs"].map((tab, index) => <button key={tab} type="button" className={`whitespace-nowrap border-b-2 px-1 pb-3 ${index ? "border-transparent" : "border-primary text-primary"}`}>{tab}</button>)}</nav>
    <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3"><Card title="Personal Information" icon={FileText}><Rows items={[["Full Name", partner.name], ["Date of Birth", partner.dateOfBirth], ["Gender", partner.gender], ["Alternate Mobile", partner.alternateMobile], ["Emergency Contact", partner.emergencyContact], ["Emergency Mobile", partner.emergencyMobile], ["Address", partner.address], ["Aadhaar Number", partner.aadhaarNumber], ["PAN Number", partner.panNumber]]} /></Card><Card title="Vehicle Information" icon={Bike}><Rows items={[["Vehicle Type", partner.vehicleType], ["Vehicle Name", partner.vehicleName], ["Vehicle Number", partner.vehicleNumber], ["RC Number", partner.rcNumber], ["Insurance Provider", partner.insuranceProvider], ["Insurance Number", partner.insuranceNumber], ["Insurance Valid Till", partner.insuranceValidTill]]} /></Card><Card title="Earnings Summary" icon={Wallet}><div className="grid grid-cols-2 gap-3">{[["Total Earnings", `₹${partner.earnings}`], ["This Week", partner.thisWeekEarnings], ["Today's Earnings", partner.todayEarnings], ["Total Payouts", partner.totalPayouts]].map(([label, item]) => <div key={label} className="rounded-lg bg-primary-light p-3"><p className="text-[11px] text-muted">{label}</p><p className="mt-1 text-sm font-semibold text-foreground">{value(item)}</p></div>)}</div></Card><Card title="Documents" icon={FileText}><div className="space-y-2 text-xs">{documents.map((document) => <div key={document} className="flex items-center gap-2"><FileText size={14} className="text-primary" /><span className="flex-1 font-medium text-foreground">{document}</span><Badge variant="success" className="h-5 px-1.5 text-[10px]">Verified</Badge><Eye size={14} className="text-muted" /></div>)}</div></Card><Card title="Bank Information" icon={Wallet}><Rows items={[["Bank Name", partner.bankName], ["Account Number", partner.accountNumber], ["IFSC Code", partner.ifscCode], ["Account Holder Name", partner.accountHolderName]]} /></Card><Card title="Recent Activity" icon={CalendarDays}><div className="space-y-3 text-xs">{activities.map((activity) => <div key={activity} className="flex items-center gap-2"><Check size={14} className="text-success" /><span className="flex-1 text-foreground">{activity}</span><span className="text-muted">{partner.lastActive}</span></div>)}</div></Card></div>
  </div></section>;
}

export default DeliveryPartner;
