import { BarChart3, CalendarDays, Download, IndianRupee, TrendingUp } from "lucide-react";
import { useMemo, useState } from "react";
import Badge from "../components/ui/Badge";
import Button from "../components/ui/Button";
import Input from "../components/ui/Input";
import Select from "../components/ui/Select";
import { transactions } from "../mock/vayzoApiMock";

const cards = [["Total Earnings", "₹12,45,678.00", IndianRupee, "+15.3%"], ["Delivery Partner Earnings", "₹8,76,320.00", TrendingUp, "+13.6%"], ["Platform Commission", "₹3,45,210.00", BarChart3, "+18.7%"], ["Refunds & Adjustments", "-₹75,852.00", CalendarDays, "-4.2%"]];
const money = (amount) => `₹${Number(amount).toLocaleString("en-IN", { minimumFractionDigits: 2 })}`;

function Earnings() {
  const [type, setType] = useState("All Earnings");
  const [fromDate, setFromDate] = useState("");
  const [toDate, setToDate] = useState("");
  const rows = useMemo(() => transactions.filter((item) => (!fromDate || item.date.slice(0, 10) >= fromDate) && (!toDate || item.date.slice(0, 10) <= toDate)).map((item) => ({ ...item, earning: item.type === "CREDIT" ? item.amount : item.type === "REFUND" ? -item.amount : 0 })), [fromDate, toDate]);
  const total = rows.reduce((sum, item) => sum + item.earning, 0);
  return <section className="min-h-full bg-background p-3 sm:p-5"><div className="space-y-4">
    <header className="flex flex-wrap items-center justify-between gap-3 border-b border-border pb-4"><div><p className="text-xs text-muted">Dashboard &gt; Earnings</p><h1 className="mt-1 text-2xl font-semibold text-foreground">Earnings</h1></div><Button variant="secondary" size="sm"><Download size={14} className="mr-1.5" />Export Report</Button></header>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([title, amount, Icon, trend]) => <div key={title} className="rounded-xl border border-border bg-surface p-3 shadow-sm"><div className="flex items-center gap-2"><Icon size={17} className="text-primary" /><span className="text-xs text-muted">{title}</span></div><div className="mt-2 flex items-end justify-between"><b className="text-lg text-foreground">{amount}</b><span className="text-[10px] text-emerald-600">↑ {trend}</span></div></div>)}</div>
    <div className="rounded-xl border border-border bg-surface p-4 shadow-sm"><div className="grid gap-3 md:grid-cols-3"><div className="grid grid-cols-2 gap-1"><Input id="earnings-from" type="date" value={fromDate} onChange={(event) => setFromDate(event.target.value)} className="h-10 min-w-0 px-2 text-[10px]" /><Input id="earnings-to" type="date" value={toDate} onChange={(event) => setToDate(event.target.value)} className="h-10 min-w-0 px-2 text-[10px]" /></div><Select id="earnings-compare" className="h-10 text-xs"><option>Previous Period</option><option>Last Month</option></Select><Select id="earnings-type" value={type} onChange={(event) => setType(event.target.value)} className="h-10 text-xs"><option>All Earnings</option><option>Partner Earnings</option><option>Commission</option><option>Refunds</option></Select></div></div>
    <div className="grid gap-4 xl:grid-cols-[1.7fr_1fr]"><div className="rounded-xl border border-border bg-surface p-4 shadow-sm"><div className="flex items-center justify-between"><h2 className="text-sm font-semibold text-foreground">Earnings Overview</h2><Badge variant="info" className="h-6">{money(total)} tracked</Badge></div><div className="mt-5 flex h-48 items-end gap-2 border-b border-border px-2">{[55, 72, 64, 82, 68, 91, 78, 96, 88].map((height, index) => <div key={index} className="group flex flex-1 flex-col items-center justify-end gap-2"><div className="w-full rounded-t bg-primary transition group-hover:bg-primary-hover" style={{ height: `${height}%` }} /><span className="text-[9px] text-muted">{12 + index} May</span></div>)}</div></div><div className="rounded-xl border border-border bg-surface p-4 shadow-sm"><h2 className="text-sm font-semibold text-foreground">Earnings by Type</h2><div className="mt-5 space-y-4 text-xs"><div><div className="mb-1 flex justify-between"><span className="text-muted">Delivery Earnings</span><b>70.4%</b></div><div className="h-2 rounded-full bg-primary-light"><div className="h-2 w-[70%] rounded-full bg-primary" /></div></div><div><div className="mb-1 flex justify-between"><span className="text-muted">Platform Commission</span><b>27.7%</b></div><div className="h-2 rounded-full bg-blue-100"><div className="h-2 w-[28%] rounded-full bg-blue-500" /></div></div><div><div className="mb-1 flex justify-between"><span className="text-muted">Other Earnings</span><b>1.9%</b></div><div className="h-2 rounded-full bg-orange-100"><div className="h-2 w-[8%] rounded-full bg-orange-400" /></div></div></div></div></div>
    <div className="rounded-xl border border-border bg-surface p-4 shadow-sm"><h2 className="text-sm font-semibold text-foreground">Earnings Summary</h2><div className="mt-3 overflow-hidden"><table className="w-full table-fixed text-left text-xs"><thead className="bg-primary-light"><tr>{["Earning Type", "This Period", "Previous Period", "Change"].map((head) => <th key={head} className="px-2 py-3 font-semibold text-foreground">{head}</th>)}</tr></thead><tbody>{[["Delivery Partner Earnings", "₹8,76,320.00", "₹7,72,310.00", "+13.47%"], ["Platform Commission", "₹3,45,210.00", "₹2,90,850.00", "+18.71%"], ["Other Earnings", "₹24,148.00", "₹19,632.00", "+22.99%"], ["Refunds & Adjustments", "-₹75,852.00", "-₹61,254.00", "-23.82%"]].filter((row) => type === "All Earnings" || row[0].toLowerCase().includes(type.split(" ")[0].toLowerCase())).map((row) => <tr key={row[0]} className="border-t border-border"><td className="truncate px-2 py-3 text-muted">{row[0]}</td><td className="px-2 py-3 font-medium text-foreground">{row[1]}</td><td className="px-2 py-3 text-muted">{row[2]}</td><td className="px-2 py-3 text-emerald-600">{row[3]}</td></tr>)}</tbody></table></div></div>
  </div></section>;
}

export default Earnings;
